name: markdown-linting

on:
  push:
    branches: 
      - '**'
  pull_request:
    branches: 
      - '**'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.base.ref }}
      - name: Update npm
        run: npm install -g npm@latest
      - name: Install markdownlint-cli
        run: npm install -g markdownlint-cli
      - name: Lint Markdown files
        run: markdownlint --reporter github-pr-check
