name: markdown-linting

on:
  push:
    branches: 
      - '**'
  pull_request:
    branches: 
      - '**'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Get changed files
        id: changed_files
        run: |
         files=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep '\.md$')
          echo "Changed files: $files"
          echo "::set-output name=files::$files"
      
      - name: Markdown Linter
        uses: DavidAnson/markdownlint-cli2-action@v15
        with:
          globs: ${{ steps.changed_files.outputs.files }}
