# This is workflow for spell checking using PySpelling lib (https://pypi.org/project/pyspelling/)
name: Spellcheck

on:
  push:
    branches: 
      - '**'
  pull_request:
    branches: 
      - '**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Get changed files
        run: |
          echo "CHANGED_FILES=$(gh pr diff ${{ github.event.number }} --name-only HEAD^ HEAD)" >> $GITHUB_ENV
      
      - name: List files
        run: |
          echo ${{ env.CHANGED_FILES }}
      - name: Spellcheck
        uses: igsekor/pyspelling-any@v1.0.4
        env:
          MATRIX: ${{ env.CHANGED_FILES }}
          
